version: 0.0
os: linux
files:
  - source: /petclinic.war
    destination: /opt/apache-tomcat-9.0.40/webapps
hooks:
  ApplicationStop:
    - location: stop_tomcat.sh
      timeout: 300
  ApplicationStart:
    - location: start_tomcat.sh
      timeout: 300
